Fix issue Snake freezes after eating last fruit
martin-ramos/nSnake pull request #4
Opened 2018-07-02 15:05 UTC by lrrinaudo

Also add the translation to spanish of winning dialog

2018-07-03 12:05 UTC, josx commented on src/Entities/Board.cpp
> -
No esta bueno que borres un enter al final del archivo, quizás en el proyecto tengan enter al final. Y si está mal esto deberia estar indicado como un commit independiente.

2018-07-03 12:11 UTC, josx commented on src/Entities/Game.cpp
> +	if((this->player->getSize() - 1) >= ((this->board->getW()) * (this->board->getH())))
Este if no deberia estar en la Entitie del Board para hacerlo mejor?

2018-07-03 12:13 UTC, josx commented on src/Entities/Game.cpp
> +		Dialog::show(_("You win"));
Este nuevo mensaje del programa es necesario, ¿por que antes no lo tenian?

2018-07-03 14:08 UTC, martin-ramos commented on src/Entities/Game.cpp
> +	if((this->player->getSize() - 1) >= ((this->board->getW()) * (this->board->getH())))
Por lo general, en el desarrollo del juego, en la Entiti Game, en el metodo update controla si la "lombriz" isAlive, y toma acciones sobre el juego. 
Es el Game, el responsable de tomar acciones tanto de perder como de ganar, por eso se decidió ponerlo de esta manera.

2018-07-03 14:10 UTC, martin-ramos commented on src/Entities/Game.cpp
> +		Dialog::show(_("You win"));
Este mensaje, no existía en el juego, desconocemos el porqué, pero el juego nunca terminaba, se rompía cuando la lombriz queria crecer mas que el tablero. Esta funcionalidad corrige ese problema, el dialogo lo agregamos porque consideramos que si la lombriz ocupa todo el tablero se gana el juego, y no se "freeza"

2018-07-03 14:23 UTC, martin-ramos requested changes
Agreguemos enter final en Board.cpp, linea 241

2018-07-03 14:35 UTC, martin-ramos approved these changes

2018-07-03 16:52 UTC, josx commented on src/Entities/Game.cpp
> +	if((this->player->getSize() - 1) >= ((this->board->getW()) * (this->board->getH())))
ok entonces ahora siempre aparecera el mensaje de ganaste.

2018-07-03 16:52 UTC, josx commented on src/Entities/Game.cpp
> +		Dialog::show(_("You win"));
ok entonces ahora siempre aparecera el mensaje de ganaste.

2018-07-03 16:56 UTC, josx commented on src/Entities/Game.cpp
> +	if((this->player->getSize() - 1) >= ((this->board->getW()) * (this->board->getH())))
Ok como digas, yo hubiera puesta la multiplicación de W * H en el entity de BOARD  como una propiedad calculada y el getSize - 1 quizas tambien directamente en player, solo hacer ese condicional en game como decis.

2018-07-03 16:58 UTC, martin-ramos commented on src/Entities/Game.cpp
> +		Dialog::show(_("You win"));
Claro, cuando la lombriz ocupa todo el tablero, el juego esta ganado, antes eso se freezaba, ahora muestra el mensaje de haber ganado

2018-07-03 17:04 UTC, martin-ramos requested changes
Hagamos que getW y getH sean propiedades, sea un calculo directamente del Board.  
Que el player devuelva el getSize() - 1 como un metodo propio del player.
De esta manera en el IF llamamos a metodo de board y de player sin calculo auxiliar.

2018-07-03 17:09 UTC, josx commented on src/Entities/Game.cpp
> +		Dialog::show(_("You win"));
perfecto!

2018-07-03 17:10 UTC, josx commented
ok dale

2018-07-03 19:24 UTC, martin-ramos approved these changes

2018-07-04 12:11 UTC, josx commented
ok che, me parecio muy gracioso el metodo getSizeMinus.
Por mi pueden empezar el proceso de abrir un PR en el proyecto original

2018-07-04 12:12 UTC, josx commented
Además recuerden que tienen un PR abierto ahi

2018-07-04 14:17 UTC, merged

2018-07-04 14:28 UTC, martin-ramos commented
Estaria mal que lo hagamos en el mismo PR que tenemos abierto?, la idea sería comentar en el ISSUE con que PR se soluciona el mismo. ¿Como lo manejamos eso?